name: Upgrade Tailwind
on: workflow_dispatch
jobs:
  upgrade-tailwindcss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '15'
      - run: |
          npm install tailwindcss@latest tailwindcss-insiders@npm:tailwindcss@insiders --save-exact --legacy-peer-deps
      - run: |
          NEW_VERSION=$(git diff -- package.json | sed -n 's/^\+.*\"tailwindcss\": \"\([^\"]*\).*$/\1/p')
          NEW_INSIDERS_VERSION=$(git diff -- package.json | sed -n 's/^\+.*\"tailwindcss-insiders\": \"npm:tailwindcss@\([^\"]*\).*$/\1/p')
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "NEW_INSIDERS_VERSION=$NEW_INSIDERS_VERSION" >> $GITHUB_ENV
      - if: ${{ env.NEW_VERSION && env.NEW_INSIDERS_VERSION }}
        run: echo "PR_TITLE=\"Upgrade \`tailwindcss\` to v$NEW_VERSION, \`insiders\` to v$NEW_INSIDERS_VERSION\"" >> $GITHUB_ENV
      - if: ${{ env.NEW_VERSION && env.NEW_INSIDERS_VERSION == '' }}
        run: echo "PR_TITLE=\"Upgrade \`tailwindcss\` to v$NEW_VERSION\"" >> $GITHUB_ENV
      - if: ${{ env.NEW_VERSION == '' && env.NEW_INSIDERS_VERSION }}
        run: echo "PR_TITLE=\"Upgrade \`insiders\` to v$NEW_INSIDERS_VERSION\"" >> $GITHUB_ENV
      - if: ${{ env.PR_TITLE }}
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: ${{ env.PR_TITLE }}
